In [2]:
import pandas as pd

# Q1: Create the dataset
raw_data = {
    "Tid": list(range(1, 11)),
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced", "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K", "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(raw_data)
df.index.name = "Index"
print("Dataset:")
display(df)

# Q2: Locate rows 0, 4, 7, and 8
print("Rows 0, 4, 7, and 8:")
display(df.loc[[0, 4, 7, 8]])

# Q3.1: Select rows from index 3 to 7, inclusive
print("1. Rows from index 3 to 7:")
display(df.loc[3:7])

# Q3.2: Select rows from index 4 to 8 and columns 2 to 4, inclusive
print("2. Rows 4 to 8 and columns 2 to 4:")
display(df.iloc[4:9, 2:5])

# Q3.3: Select all rows with column indexes 1 to 3, inclusive
print("3. All rows with column indexes 1 to 3:")
display(df.iloc[:, 1:4])

Dataset:

       Tid Refund Marital Status Taxable Income Cheat
Index
0        1    Yes         Single           125K    No
1        2     No        Married           100K    No
2        3     No         Single            70K    No
3        4    Yes        Married           120K    No
4        5     No       Divorced            95K   Yes
5        6     No        Married            60K    No
6        7    Yes       Divorced           220K    No
7        8     No         Single            85K   Yes
8        9     No        Married            75K    No
9       10     No         Single            90K   Yes

Rows 0, 4, 7, and 8:

       Tid Refund Marital Status Taxable Income Cheat
Index
0        1    Yes         Single           125K    No
4        5     No       Divorced            95K   Yes
7        8     No         Single            85K   Yes
8        9     No        Married            75K    No

1. Rows from index 3 to 7:

       Tid Refund Marital Status Taxable Income Cheat
Index
3        4    Yes        Married           120K    No
4        5     No       Divorced            95K   Yes
5        6     No        Married            60K    No
6        7    Yes       Divorced           220K    No
7        8     No         Single            85K   Yes

2. Rows 4 to 8 and columns 2 to 4:

      Marital Status Taxable Income Cheat
Index
4           Divorced            95K   Yes
5            Married            60K    No
6           Divorced           220K    No
7             Single            85K   Yes
8            Married            75K    No

3. All rows with column indexes 1 to 3:

      Refund Marital Status Taxable Income
Index
0        Yes         Single           125K
1         No        Married           100K
2         No         Single            70K
3        Yes        Married           120K
4         No       Divorced            95K
5         No        Married            60K
6        Yes       Divorced           220K
7         No         Single            85K
8         No        Married            75K
9         No         Single            90K

In [4]:
df_csv = pd.read_csv("iris.csv")
df_csv.head(3)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [5]:
# Q5: Delete row 4 and column 3 from the CSV DataFrame
q5_result = df_csv.drop(index=df_csv.index[4]).drop(columns=df_csv.columns[3])

print("Result after deleting row 4 and column 3:")
display(q5_result)

Result after deleting row 4 and column 3:

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

In [6]:
# Q6: Create and save the employee dataset
import pandas as pd

employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

employees_df = pd.DataFrame(employee_data)
employees_df.to_csv("employees.csv", index=False)
display(employees_df)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [7]:
# Q6(a-b): Inspect the DataFrame
print("Shape:", employees_df.shape)
print("Summary:")
employees_df.info()

Shape: (5, 10)
Summary:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 532.0 bytes

In [8]:
# Q6(c-d): Descriptive statistics and selected rows
print("Descriptive statistics:")
display(employees_df.describe())

print("First five rows:")
display(employees_df.head())

print("Last three rows:")
display(employees_df.tail(3))

Descriptive statistics:

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

First five rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last three rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [9]:
# Q6(e): Calculate the requested statistics
print("Average salary:", employees_df["Salary"].mean())
print("Total bonus:", employees_df["Bonus"].sum())
print("Youngest employee age:", employees_df["Age"].min())
print("Highest performance rating:", employees_df["Rating"].max())

Average salary: 60000.0
Total bonus: 27500
Youngest employee age: 28
Highest performance rating: 4.7

In [10]:
# Q6(f): Sort employees by salary in descending order
employees_sorted = employees_df.sort_values(by="Salary", ascending=False)
display(employees_sorted)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [11]:
# Q6(g): Categorize employees by performance rating
employees_df["Performance_Category"] = "Average"
employees_df.loc[employees_df["Rating"] >= 4.5, "Performance_Category"] = "Excellent"
employees_df.loc[(employees_df["Rating"] >= 4.0) & (employees_df["Rating"] < 4.5), "Performance_Category"] = "Good"
display(employees_df[["Name", "Rating", "Performance_Category"]])

      Name  Rating Performance_Category
0    Alice     4.5            Excellent
1      Bob     4.0                 Good
2  Charlie     3.8              Average
3    Diana     4.7            Excellent
4   Edward     3.5              Average

In [12]:
# Q6(h-j): Missing values, rename, and employee filters
print("Missing values:")
display(employees_df.isnull().sum())

employees_df = employees_df.rename(columns={"Employee_ID": "ID"})
print("Employees with more than 5 years of experience:")
display(employees_df[employees_df["Years_of_Experience"] > 5])

print("Employees in the IT department:")
display(employees_df[employees_df["Department"] == "IT"])

Missing values:

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

Employees with more than 5 years of experience:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

Employees in the IT department:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [13]:
# Q6(k-l): Add tax and save the modified DataFrame
employees_df["Tax"] = employees_df["Salary"] * 0.10
employees_df.to_csv("employees_modified.csv", index=False)
print("Modified dataset saved as employees_modified.csv")
display(employees_df)

Modified dataset saved as employees_modified.csv

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0